version: "3.8"
services:
  scheduler_api:
    image: scheduler_api:latest
    container_name: scheduler_api
    user: root
    depends_on:
      - redis
      - celery_worker
    environment:
      - REDIS_HOST=redis
      - MAX_SECONDS=31536000
    build:
      context: ./
    ports:
      - "80:80"
    networks:
      - scheduler_network
#    volumes:
#       - ./:/home/ubuntu/fast_api/

  redis:
    image: redis:7.4.2
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - scheduler_network

  celery_worker:
    image: scheduler_api:latest
    build:
      context: ./
    container_name: celery_worker
    command: celery -A celery_tasks.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
#    volumes:
#       - ./:/home/ubuntu/fast_api/
    networks:
      - scheduler_network

networks:
  scheduler_network:
    name: scheduler_network
